version: "3"

services:
  app:
    build: ./fleetly.app-server
    container_name: fleetly-app
    env_file: .env
    environment:
      # DB
      - DB_HOST=$DB_HOST
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
      # DB credentials
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      # JWT
      - JWT_EXPIRES_IN=1h
      - JWT_SECRET=fleetly
      # Server
      - NODE_ENV=development
      - PORT=$PORT
    image: nodejs
    links:
      - db
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./fleetly.app-server:/usr/src/app

  db:
    command: [--auth]
    container_name: fleetly-db
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db

volumes:
  dbdata:
