version: "3"

services:
  app:
    container_name: fleetly-app
    env_file: .env.development.local
    environment:
      # DB
      - DB_HOST=$DB_HOST
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
      # DB credentials
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      # JWT
      - JWT_EXPIRES_IN=1h
      - JWT_SECRET=fleetly
      # Server
      - NODE_ENV=production
      - PORT=$PORT
    image: fleetly/fleetly.app-server
    links:
      - db
    ports:
      - "80:8080"
    restart: always

  db:
    command: [--auth]
    container_name: fleetly-db
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - dbdata:/data/db

volumes:
  dbdata:
